# Generated by Django 4.1.7 on 2023-06-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_cateogory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
